#!/bin/bash
#****************************************************************************
#* EDAPack wrapper script for SymbiYosys
#****************************************************************************

# First, determine the location of this script
if test -f $0; then
  script_dir=$(dirname $0)
  script_dir=$(cd $script_dir ; pwd)
else
  # Find ourselves in the PATH
  for elem in $(echo PATH | sed -e 's%:% %g'); do
    script=${elem}/$0
    if test -f $script; then
      script_dir=$elem
      break
    fi
  done
fi

EDAPACK_SBY=$(dirname $script_dir)
EDAPACK=$(dirname $(dirname $EDAPACK_SBY))

# Ensure we can find the python3 install
export PATH=$EDAPACK/python3/bin:$PATH


# Ensure SymbiYosys finds its sub-components
export PATH=$EDAPACK_SBY/symbiyosys/bin:$PATH
export LD_LIBRARY_PATH=$EDAPACK_SBY/symbiyosys/lib:$LD_LIBRARY_PATH

exec $EDAPACK_SBY/symbiyosys/bin/sby ${@:1}

