#!/bin/sh
#****************************************************************************
#* EDAPack wrapper script for SymbiYosys
#****************************************************************************

# First, determine the location of this script
if test -f $0; then
  script_dir=$(dirname $0)
  script_dir=$(cd $script_dir ; pwd)
else
  # Find ourselves in the PATH
  for elem in $(echo PATH | sed -e 's%:% %g'); do
    script=${elem}/$0
    if test -f $script; then
      script_dir=$elem
      break
    fi
  done
fi

EDAPACK=$(dirname $script_dir)

# Ensure SymbiYosys finds its sub-components
export PATH=$EDAPACK/symbiyosys/bin:$PATH

exec $EDAPACK/symbiyosys/bin/sby ${@:1}

